# BLUE VERSION (Stable)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args: ["-text=Welcome to the BLUE Version"]
        ports:
        - containerPort: 5678
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# GREEN VERSION (New Release)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: default
spec:
  replicas: 1 # Start with 1 replica for Canary testing
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args: ["-text=Welcome to the GREEN Version"]
        ports:
        - containerPort: 5678
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# THE SERVICE (Azure Load Balancer)
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: LoadBalancer # Changed from NodePort to get a Public IP in Azure
  selector:
    app: myapp
    # version: blue  <-- COMMENT THIS OUT to enable Canary (75% Blue / 25% Green)
    # version: green <-- UNCOMMENT THIS to complete Blue-Green (100% Green)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678